vich_uploader:
    db_driver: orm

    mappings:
        carte_membre:
            uri_prefix: /images/carte_membre/photos
            upload_destination: '%kernel.project_dir%/public/images/carte_membre/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
